name: Run lint and type checks

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
   runs-on: ubuntu-latest    

   steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
       node-version: 20
    - run: pnpm i
    - run: pnpm run check-types
    - run: pnpm run lint